networks:
  own_network:
    driver: bridge

secrets:
  db_root_password:
    file: ./secrets/db_root_password.txt
  db_user_password:
    file: ./secrets/db_user_password.txt
  wp_admin_password:
    file: ./secrets/wp_admin_password.txt
  wp_user_password:
    file: ./secrets/wp_user_password.txt

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/home/fceragio/mariadb"
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/home/fceragio/wordpress"


services:
  mariadb:
    container_name: mariadb
    image: mariadb
    env_file: .env
    build: ./requirements/mariadb
    restart: always
    secrets:
      - db_root_password
      - db_user_password
    volumes:
      - mariadb_data:/var/lib/mysql:rw
    networks:
      - own_network

  wordpress:
    container_name: wordpress
    image: wordpress
    env_file: .env
    build: ./requirements/wordpress
    restart: always
    secrets:
      - db_user_password
      - wp_admin_password
      - wp_user_password
    volumes:
      - wordpress_data:/var/www/wordpress:rw
    networks:
      - own_network
    depends_on:
      - mariadb

  nginx:
    container_name: nginx
    image: nginx
    env_file: .env
    build:
      context: ./requirements/nginx
      args:
        - DOMAIN_NAME=${DOMAIN_NAME}
        - CERTS=${CERTS}
    restart: always
    volumes:
      - wordpress_data:/var/www/wordpress:rw
    networks:
      - own_network
    ports:
      - "443:443"
    depends_on:
      - wordpress

